CREATE TABLE CLIENTE (
  	ID_Cliente TEXT PRIMARY KEY,
  	Nombre TEXT NOT NULL,
  	Direccion TEXT NOT NULL,
  	Telefono TEXT NOT NULL
);
CREATE TABLE EMPLEADO (
	ID_Empleado TEXT PRIMARY KEY,
  	Nombre TEXT NOT NULL,
  	Telefono TEXT NOT NULL,
  	Usuario TEXT NOT NULL UNIQUE,
  	Contrasena TEXT NOT NULL,
  	Es_Admin INTEGER NOT NULL,
  	Salario TEXT NOT NULL,
	Es_Activo INTEGER NOT NULL
);
CREATE TABLE PRODUCTO (
	ID_Producto TEXT PRIMARY KEY,
  	Nombre TEXT NOT NULL,
  	Precio REAL NOT NULL,
  	Stock INTEGER NOT NULL
);
CREATE TABLE FACTURA (
	ID_Factura TEXT PRIMARY KEY,
  	ID_Cliente TEXT NOT NULL,
  	ID_Empleado TEXT NOT NULL,
  	Fecha TEXT NOT NULL,
  	Hora TEXT NOT NULL,
    ID_Transaccion TEXT,
  	Total REAL NOT NULL,
  	FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE(ID_Cliente),
  	FOREIGN KEY (ID_Empleado) REFERENCES EMPLEADO(ID_Empleado)
);
CREATE TABLE DETALLE (
	ID_Factura TEXT,
  	ID_Producto TEXT,
  	Cantidad INTEGER NOT NULL,
  	Valor REAL NOT NULL,
    PRIMARY KEY (ID_Factura, ID_Producto),
  	FOREIGN KEY (ID_Factura) REFERENCES FACTURA(ID_Factura),
  	FOREIGN KEY (ID_Producto) REFERENCES PRODUCTO(ID_Producto)
);
CREATE TABLE DEVOLUCION (
	ID_Factura TEXT,
  	ID_Producto TEXT,
  	Fecha TEXT NOT NULL,
  	Hora TEXT NOT NULL,
    PRIMARY KEY (ID_Factura, ID_Producto),
    FOREIGN KEY (ID_Factura) REFERENCES FACTURA(ID_Factura),
    FOREIGN KEY (ID_Producto) REFERENCES PRODUCTO(ID_Producto)
);